### PR TITLE
1451-1500 review and fixes - 

### PR DESCRIPTION
**Pull request by cedricske**

### CODE REVIEW

**Comment by doktorsleepelss** [comment]
Anyone know why checks aren't running on this one?

**Comment by pjlao307** [comment]
Not sure what the deal is, try resubmitting or do a simple push to the PR and see if it kicks off again.

**Comment by doktorsleepelss** [comment]
Pretty much every single mask in this one has issues. There's a bunch of random polygons all over the place.

**Comment by cedricske** [comment]
I've been doing it the same way that worked the first 400 images or so. The only thing I can think of that I might have changed is that I'm not saving them to my computer any more as a back up :(

Current process: create branch from master for section I'm going to review (1400-1450) > open up imgLabeler and type in 1400 and load the current mask > review and make changes > commit to branch > repeat. 

I think I used to save them to my computer as a backup before committing them, that's all I can think of. Not excited to re-review all these images...

**Comment by doktorsleepelss** [comment]
Yeah, like I said your in your other PR, commit to branch has always been broken for me for reviews.  I'm surprised it worked for you for the first 400.

**Comment by doktorsleepelss** [comment]
Revert from History still not working either?

**Comment by doktorsleepelss** [comment]
Closing to declutter.  Open a new PR if you get fix them.

**Pull request closed without merging**
