### PR TITLE
Updated mask for 0237_8443d7dd0ec9bd92_2018-08-31--22-04-01_16_300

### PR DESCRIPTION
**Pull request by brittonx**

### CODE REVIEW

**Comment by VirtuallyChris** [comment]
This image has anti-aliasing all over it making it have more than 5 colors. Use the pencil tool and disable anti-aliasing when doing selections and fills so the edges are hard.

**Comment by pjlao307** [comment]
The file still has bad colors that need to be fixed.

**Comment by pjlao307** [comment]
Is this still being worked on?

**Comment by brittonx** [comment]
Hi!
Yes, I should get through this one and the others I claimed in the next day
or two.

**Comment by pjlao307** [comment]
I'm going to close this one so someone else can grab it.

**Pull request closed without merging**
