### PR TITLE
162e

### PR DESCRIPTION
**Pull request by hug0hq**
this is my first one, let me know if is everything ok

### CODE REVIEW

**Comment by pjlao307** [comment]
Is this still being worked on?  Why was it closed?  Also, please update the spreadsheet to reflect the correct status.

**Comment by hug0hq** [comment]
@pjlao307 sorry for the delay, the reviewer is broken on firefox and i thought i did something wrong with the image but its ok on chrome.

**Comment by pjlao307** [comment]
Looks like your mask is the wrong dimension.

**Comment by pjlao307** [comment]
Almost there... this isn't a lane line, it doesn't line up with the other lines for that lane
image

**Comment by Polydynamical** [comment]
Someone with write status needs to approve this PR for the checks to start running (@pjlao307 or @doktorsleepelss )

**Review by Polydynamical — APPROVED** [review]

**Pull request merged**
