### PR TITLE
818,820,821

### PR DESCRIPTION
**Pull request by uselessinfodude**

### CODE REVIEW

**Comment by pjlao307** [comment]
Why does this PR list 3 images but there are 12 files modified?

**Comment by uselessinfodude** [comment]
No idea, I'm guessing it's still sending the files I sent in my last PR even though I created a new branch, edited these 3 files and committed/pushed from that branch.

**Comment by pjlao307** [comment]
You need to rebase master, then create an new branch from master so it has the latest files.
To do that you need to checkout master, then when you create a new branch it will be based off of master, not your other branch that may have different files.

**Comment by uselessinfodude** [comment]
I'm using sourcetree and not exactly sure how to 'rebase' master. The only option I'm seeing is 'rebase current changes onto master' which I believe you said before is not correct.

**Comment by pjlao307** [comment]
Your master is currently 7 commits behind Comma's.  I don't use sourcetree but the discord channel has the commands to do it via command line.

**Pull request closed without merging**
