### PR TITLE
0090 russbb02

### PR DESCRIPTION
**Pull request by russbb02**

### CODE REVIEW

**Comment by pjlao307** [comment]
Looks like CI is stuck for this PR.

**Comment by russbb02** [comment]
> Looks like CI is stuck for this PR.

Do I need to do anything to fix this?  I need to know if i made a mistake so i dont repeat it.

**Comment by pjlao307** [comment]
Not sure why it's stuck, you may try closing this and resubmitting the PR.

**Comment by pjlao307** [comment]
I looked at the file itself and the problem it has is the dimensions are wrong.  It's resized to a much larger size.  It should be 1164x874.

**Pull request closed without merging**
