### PR TITLE
2285 to 2289

### PR DESCRIPTION
**Pull request by quantumsnow**
2285 to 2289

### CODE REVIEW

**Comment by pjlao307** [comment]
The size of these masks changed.   They must be the same as the original masks.  Make sure you're not zoomed in/out when saving masks in img-labeler.

**Comment by quantumsnow** [comment]
Hm, I'm not zoomed. Could it have to do with Windows UI scaling?

**Comment by pjlao307** [comment]
There should be no scaling either.

**Comment by quantumsnow** [comment]
Ah, ok. I'll do that. But that's a shame, I don't know that I'll be able to do more then if I have to switch off scaling every time 😕

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/1417

**Pull request closed without merging**
