### PR TITLE
3671 cleanup

### PR DESCRIPTION
**Pull request by Spacefish**

### CODE REVIEW

**Comment by Spacefish** [comment]
ah damn.. the included tool did some interpolation when drawing on the canvas in my browser.. i update the commit later on.

**Comment by pjlao307** [comment]
The pencil tool is crappy, use img-labeler.

**Comment by Spacefish** [comment]
> The pencil tool is crappy, use img-labeler.

yep, redid the image with img-labeler

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/1718

**Pull request closed without merging**
