### PR TITLE
237,320,417

### LINKED ISSUE #558: 237,320,417- bigbalthazor
i can fix my own issues.

### PR DESCRIPTION
**Pull request by bigbalthazor**
closes #558

### CODE REVIEW

**Comment by VirtuallyChris** [comment]
Glitch happened on 237 too! strange

**Comment by spektor56** [comment]
on 417 aswell

**Comment by bigbalthazor** [comment]
> on 417 aswell
what the issue?

**Comment by spektor56** [comment]
Look at the road, it goes all the way to the left in your commit

**Pull request merged**
