### PR TITLE
Viewer enhancements

### PR DESCRIPTION
**Pull request by gregjhogan**
* left/right arrows for back/forward navigation
* up/down arrows for mask opacity
* m to toggle mask
* q or escape to quit

### CODE REVIEW

**Comment by pjlao307** [comment]
Nice.
A couple other features that would make reviewing faster is a toggle for the mask because somethings it's hard to see how accurate the mask is while it's overlaid on the image and maybe a zoom and pan to look at the details.  This is what I do in photoshop when reviewing PRs.

**Comment by gregjhogan** [comment]
yeah I was thinking the same thing about the mask, so added up/down arrows for mask and `m` for toggle

not exactly sure how to add the zoom/pan, will be a good next enhancement

**Comment by pjlao307** [comment]
Are you able to merge this or would you need me to?

**Comment by gregjhogan** [comment]
I will merge it if CI ever passes! seems stuck

**Comment by gregjhogan** [comment]
github actions seems to be experiencing issues for the last couple hours, but since this PR doesn't touch anything that the tests check I am going to merge.

**Pull request merged**
