### PR TITLE
add masksd 108-110

### PR DESCRIPTION
**Pull request by AlexandreSato**

### CODE REVIEW

**Comment by kevinharbin** [comment]
Driver's hand through the wheel should be marked

**Comment by AlexandreSato** [comment]
Is it not the steering wheel?  from the other pictures it appears to be.



Em 19 de set. de 2022, à(s) 16:06, kevinharbin ***@***.***> escreveu:

﻿

Driver's hand through the wheel should be marked

**Comment by kevinharbin** [comment]
I'm looking at this. Looks hand colored.
image
image

**Comment by kevinharbin** [comment]
109, is this a pole in front of the truck?
image
I think this is a raised curb so not actually drivable. Take a second look and you make the call.
image
no comments on 110

**Comment by AlexandreSato** [comment]
> 109, is this a pole in front of the truck?
> I think this is a raised curb so not actually drivable. Take a second look and you make the call. 
 no comments on 110


I think you're right, but I'm not sure. Anyway, I've already made the changes, if anyone else can confirm we'd appreciate it.

**Pull request merged**
