### PR TITLE
960 - 969

### LINKED ISSUE #490: 960 - 969 meh-meh

### PR DESCRIPTION
**Pull request by meh-meh**
Closes #490

### CODE REVIEW

**Comment by meh-meh** [comment]
Issue #490

**Comment by meh-meh** [comment]
Closes #490

**Comment by pjlao307** [comment]
FYI you need to put that into the original comment for the PR for it to link.

**Comment by meh-meh** [comment]
Made the requested changes except for 965. I can see a smudgy lane marking there, so I labelled it.

**Pull request merged**
