### PR TITLE
[381-385, 394-398] - h2code

### PR DESCRIPTION
**Pull request by hassanhibbert**

### CODE REVIEW

**Comment by hassanhibbert** [comment]
I wasn't sure if those were actually head lights or a couple of short plaza lights since it looked like poles underneath. I'll still update though.

**Comment by hassanhibbert** [comment]
Everything should be good to go with this set up masks.

**Comment by pjlao307** [comment]
You keep including the same masks in multiple PRs.  394-398 are already in this PR: https://github.com/commaai/comma10k/pull/356

When working on different batches make sure the new branch doesn't have the same modified files from your other branch(es).

Please revert 394-398 from this branch.

**Comment by pjlao307** [comment]
This is why you don't want to include the same changes in multiple PRs.  Now this PR has conflicts.

**Comment by hassanhibbert** [comment]
close and refer to #394

**Pull request closed without merging**
