### PR TITLE
00173f

### PR DESCRIPTION
**Pull request by albertorestifo**
My second attempt at masking, `00173f`

### CODE REVIEW

**Comment by albertorestifo** [comment]
I need to make some improvements to one line on the left.

**Comment by albertorestifo** [comment]
Done

**Review by Polydynamical — APPROVED** [review]

**Comment by pjlao307** [comment]
I think the part that is in the shadow is undrivable if you compare it to where the shadow is below it (it's in the snow).

**Comment by albertorestifo** [comment]
@pjlao307 had to draw the line there, the is not enough detail.

One on hand, if the part in the shadow is covered in snow, there wouldn't be any space for that right lane that is just starting in the frame, and I find it weird that they cleared the road that way, bulging back inside the road

**Comment by pjlao307** [comment]
I would disagree, you can see where that suv is in the distance in that lane, there is enough room and you can see the edge of the lane where the white (snow) is past the shadow.

image

**Comment by pjlao307** [comment]
For comparison, the proportion of the road when it curves like that is consistent.
image

That part in the shadow is the shoulder.  They wouldn't suddenly have no shoulder going into the turn.

**Comment by albertorestifo** [comment]
@pjlao307 I extended the right side, can you check the changes?

**Pull request merged**
