### PR TITLE
added masks SA 700-799

### PR DESCRIPTION
**Pull request by Umbrasi**

### CODE REVIEW

**Comment by pjlao307** [comment]
700 - The hood of the car is not accurate, missing the top part of the center.
image

This is not part of the bus, this looks like a building.
image

The part of the curb that meets the road should be drivable.
image

**Comment by pjlao307** [comment]
702 - Missing cars in the distance and the right lane line needs to be more accurate
image

The far right lane line needs to be extended farther out.
image

**Comment by pjlao307** [comment]
703 - The shadow is part of the road, not the barrier.
image

This is not 1 long lane line, it's 2 separate lines.
image

Undrivable needs to be more accurate, this part is road.
image

**Comment by pjlao307** [comment]
707 - Missing person in the middle of the street.
image

**Comment by pjlao307** [comment]
708 - Missing cars
image

**Comment by pjlao307** [comment]
709 - Missing more lane line in the distance.
image

Lane line needs to be more accurate.
image

**Comment by pjlao307** [comment]
712 0 Lane lines need to be more accurate.
image

Missing lane line on the left.
image

Lane line in the distance needs to be more accurate and missing a car.
image

Also missing these cars.
image

**Comment by geohot** [comment]
Nice job!

It's fixing these wrongly labelled pixels that lead to super high segnet accuracies. The model is always thinking "zoomed in"

(re objective/subjective per our discussion, the missing cars for example are in my opinion something that is completely objective, and the sort of thing I expect to find in max 1 out of 10)

**Comment by doktorsleepelss** [comment]
I would grab more of thee pixels of these far away lane lines.

**Comment by doktorsleepelss** [comment]
Something like this.

**Comment by doktorsleepelss** [comment]
https://i.imgur.com/zEO1pkx.jpg

**Comment by geohot** [comment]
Yea, pixels on the edge like that going with the lane line class is a good choice.

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/1896

**Pull request closed without merging**
