### PR TITLE
1044 terror

### PR DESCRIPTION
**Pull request by terror**

### CODE REVIEW

**Comment by pjlao307** [comment]
Please fix color issue

**Comment by terror** [comment]
> Please fix color issue

I'm using the img labeler tool over at https://erikbernheim.github.io/img-labeler/ with chrome on MacOS. Any suggestions on how to fix color issue?

**Comment by pjlao307** [comment]
Not sure, I haven't had any issues with colors using img-labeller but I'm on windows.

You've also got the file in 2 places, remove the one that's above the masks/ folder.

**Comment by pjlao307** [comment]
May want to ask in the comma-pencil channel.

**Comment by terror** [comment]
I'll reattempt in a new pr

**Pull request closed without merging**
