### PR TITLE
[1049] Jax05

### PR DESCRIPTION
**Pull request by Jax05**

### CODE REVIEW

**Comment by Jax05** [comment]
I'm unable to fix the colors despite using the img-labeler tool. I had to resize the image after downloading but 8-bit colors was selected on save. Any suggestions would be helpful.

**Comment by doktorsleepelss** [comment]
The reason  img-labeler sometimes saves it bigger is because you either have your browser zoomed in your're scaling up in your windows/os settings. .  Try using Revert from History, and resave it again without all the zooming/scaling disabled.

**Comment by Jax05** [comment]
@doktorsleepelss thanks for the suggestion. My scaling seemed to be fine and the image wasn't zoomed in. I saw an issue about [this](https://github.com/erikbernheim/img-labeler/issues/12) on the official repo and tried a workaround. Tests finally passed!

**Comment by meh-meh** [comment]
Please remember to claim an image on the spreadsheet before submitting, and as pjlao says, please use a branch for your PR. Either way, thank you for the contribution. Assuming their changes come through, this PR can be closed when #839 is merged.

**Comment by Jax05** [comment]
@meh-meh will do. I was under the impression we only had to claim via an issue and someone managed the spreadsheet.

@pjlao307 I'll be sure to create a branch for the updated changes. Thanks!

**Pull request closed without merging**
