### PR TITLE
255 azmisj

### PR DESCRIPTION
**Pull request by myxenium**

### CODE REVIEW

**Comment by geohot** [comment]
Careful, this file has the wrong name.

**Comment by doktorsleepelss** [comment]
Make sure to read the readme and check the spreadsheet before working on new images.  This one already has a completed mask.  No need to make a new one, but feel free to submit prs for any errors you see.  

Currently we're only working on masks from the the imgs2 and imgsd folder.

**Comment by myxenium** [comment]
Ok duly noted. Thank you very much.

/AZMI Salim

**Comment by myxenium** [comment]
Noted on that, will readup further. Thank you again.

/AZMI Salim

**Comment by myxenium** [comment]
Hi,

I have actually redo the image. It is supposed to be image id 255e inside
imgs2 series. Also created a new pull request and updated the spreadsheet.

Thank you.

Regards,
AZMI Salim

**Comment by myxenium** [comment]
New Pull request URL: https://github.com/commaai/comma10k/pull/2960

**Pull request closed without merging**
