### PR TITLE
[1190-1195] sshireto

### PR DESCRIPTION
**Pull request by sshireto**

### CODE REVIEW

**Comment by sshireto** [comment]
a

**Comment by mutusmurum** [comment]
Resubmitted and merged on PR: https://github.com/commaai/comma10k/pull/1047
I'm reviewing the other ones now.

**Comment by pjlao307** [comment]
1190-1193 was already submitted as part of this merge: https://github.com/commaai/comma10k/pull/1047

**Comment by mutusmurum** [comment]
Small fixes on this PR: https://github.com/commaai/comma10k/pull/1049

**Pull request closed without merging**
