### PR TITLE
[1780-1794] Qatarking24

### PR DESCRIPTION
**Pull request by Qatarking24**

### CODE REVIEW

**Comment by Qatarking24** [comment]
Done. I've created a new pull request https://github.com/commaai/comma10k/pull/1067 
Also, I'm not sure if 1786 is done properly (The hood of the car).

**Comment by pjlao307** [comment]
Don't create new PRs, just commit into the same branch and this PR will get updated so that we don't lose the comments.  Close the other PR and just make the changes in this branch.

**Comment by Qatarking24** [comment]
Done.

**Comment by Qatarking24** [comment]
done.

**Comment by Qatarking24** [comment]
Done

**Pull request merged**
