### PR TITLE
2450-2454 logiti

### PR DESCRIPTION
**Pull request by logiti**

### CODE REVIEW

**Comment by pjlao307** [comment]
This one's got bad colors on all 5 files.

**Comment by logiti** [comment]
what does that mean?

**Comment by pjlao307** [comment]
It means your file has colors that are not the 5 expected as described in the README.

**Comment by logiti** [comment]
I've tried crosschecking and it seems like everything I did is right. Any ideas on what is causing this error?

**Comment by doktorsleepelss** [comment]
Did you use imglaber?  What browser did you use? Did you use any other programs? Did you do any resizing?

**Pull request closed without merging**
