### PR TITLE
Updated masks 0001 to 0005

### PR DESCRIPTION
**Pull request by scottadair**

### CODE REVIEW

**Comment by pjlao307** [comment]
Looks like 0001 mask didn't come through correctly, it's a wall of undrivable.

**Comment by scottadair** [comment]
Hmm, I'm gonna blame GIMP.. Mask updated

**Comment by scottadair** [comment]
Sorry, cleaning up branching on my fork and accidentally deleted this branch

**Comment by doktorsleepelss** [comment]
https://github.com/commaai/comma10k/pull/2654

**Pull request merged**
