### PR TITLE
71-79

### PR DESCRIPTION
**Pull request by malawadd**

### CODE REVIEW

**Comment by pjlao307** [comment]
This PR has conflicts.  Please fix.  Make sure your branch is rebased (synced) with comma's master branch.

**Comment by malawadd** [comment]
how do i fix that ?

**Comment by pjlao307** [comment]
Easiest thing is delete your fork and re-fork from comma.  Make a copy of those files first.
Also, don't make changes directly in your master branch.  Create a new branch to work off of.

**Comment by malawadd** [comment]
but why did this happen in the first place , all what i did is copy the new files to my local repo , push then pull.

**Comment by pjlao307** [comment]
No idea, I can't go off of much other than what I'm seeing in github.

**Comment by pjlao307** [comment]
Most likely, you are submitting 1 or more files that someone else already did.

**Comment by malawadd** [comment]
71-79 are 7 days old , i dont think anyone have done them..

**Comment by pjlao307** [comment]
Whatever you did, I can't merge this so you have to figure it out.

**Pull request closed without merging**
