### PR TITLE
202-205

### PR DESCRIPTION
**Pull request by malawadd**

### CODE REVIEW

**Comment by pjlao307** [comment]
This PR has conflicts and has 13 modified files not just 202-205.

**Comment by malawadd** [comment]
why is it pulling everything i just made a pull requested earlier for 71-79 , and it was merged,   how can i do just 202-205.

**Comment by pjlao307** [comment]
You need to understand how PRs and branches work in git.  If you work on the same branch, any changes you make in that branch gets reflected in the PR.
Once you're done with a batch and your PR gets merged, you need to rebase with master (so you get the latest version of all files) then create a NEW branch from that and make your changes to that new branch.  Once you're done with those changes submit a PR from that new branch.  Don't keep using the old branch that had your old changes in it.

**Comment by malawadd** [comment]
so thats how its done , thank you so very much.

**Pull request closed without merging**
