### PR TITLE
1520 1525 cedricske

### PR DESCRIPTION
**Pull request by cedricske**

### CODE REVIEW

**Comment by pjlao307** [comment]
Looks like the file size changed in this PR.

**Comment by cedricske** [comment]
@pjlao307 - Interesting, I used the new feature in image labeler to commit changes. I will upload the images the old way.

**Comment by pjlao307** [comment]
Size still failed and there's also 1 file with bad color
image

**Comment by mutusmurum** [comment]
Fix: https://github.com/commaai/comma10k/pull/1110

**Pull request closed without merging**
