### PR TITLE
230 232 233 234 235 236 242

### LINKED ISSUE #224: 230 232 233 234 235 236 242

### PR DESCRIPTION
**Pull request by nelsonjchen**
Closes #224

### CODE REVIEW

**Comment by pjlao307** [comment]
Will there be more commits to this PR or are these all of them?

**Comment by pjlao307** [comment]
Unsure when you're done with your batch since you haven't claimed any in Issues.

**Comment by nelsonjchen** [comment]
That is it.

**Comment by nelsonjchen** [comment]
@pjlao307 Thanks for taking a look at them.

Updated all of them. @nanamiwang's GIMP plugin/setup is soooooooooooo good. I strongly recommend it. 

I am uncertain I agree with you on your 242's left arrow. That said, I've marked it per your specification.

**Pull request merged**
