### PR TITLE
[1510-1515] BornAgainGenius

### PR DESCRIPTION
**Pull request by YosanAI**

### CODE REVIEW

**Comment by pjlao307** [comment]
Looks like the size changed on 1511
image

**Comment by YosanAI** [comment]
@pjlao307  is there anyway to resize it without doing it all over again?

**Comment by YosanAI** [comment]
@pjlao307 nevermind, I found an automatically saved version in IMG labeler. now it passed the size check. but just for info is there a way to resize it?

**Comment by pjlao307** [comment]
You can in photoshop but you have to be careful not to introduce antialiasing when resizing.

**Comment by mutusmurum** [comment]
@YosanAI Your masks have many unmovable pixels all around the images. I'll fix it myself, but the careful in the next ones. If you're using photoshop, I highly suggest you use Polygonal Lasso to make the masks (with anti-aliasing disabled).

**Comment by pjlao307** [comment]
Closing this since all files are now conflicting

**Pull request closed without merging**
