### PR TITLE
Variety of dcam images

### PR DESCRIPTION
**Pull request by kevinharbin**
I just learned that I can't pull just one commit into a PR. Sorry, there are three batches of 5 images here. I'll get it right next time.
imgsd files 00065.png through 00079.png

### CODE REVIEW

**Comment by kevinharbin** [comment]
why does this have all the previous commits too? maybe I should delete this and start over. It should only be the three recent commits.

**Comment by doktorsleepelss** [comment]
oh, don't work off master. Make a new branch for every new pr you make.  I would delete your current comma10k repo and refork it.

**Comment by kevinharbin** [comment]
I'm assuming it's 10 total including the ones in b5fa144. I have picked my most diverse 10. This set of 10  probably requires deleting the ones in b5fa144. How should I number the new 10?

**Comment by doktorsleepelss** [comment]
Just delete your entire comma10k fork by going to the settings. You'll see the delete option in the "danger zone" section.

Then refork comma10k, and create a new branch.  Pick whatever 10 images you want and name them  00065.png to 00074.png

**Comment by kevinharbin** [comment]
Got it.

**Pull request closed without merging**
