### PR TITLE
updated 341, 342, 343, 344

### PR DESCRIPTION
**Pull request by tracminhvu**
Initial PR

### CODE REVIEW

**Comment by pjlao307** [comment]
May need to re-push this PR to trigger CI since it's stuck.  If that doesn't work will need to close and resubmit a new PR.

**Comment by tracminhvu** [comment]
close and reopen PR

**Comment by nelsonjchen** [comment]
It's not stuck. The check only runs on changes to the `masks/` folder. The original image files and not the mask files were changed.

**Comment by nelsonjchen** [comment]
Oh, nevermind, that PR I sent in runs color check now. That said, the issue of modifying the original images still stands.

**Comment by tracminhvu** [comment]
Yes, this branch has problem of img changed unintentionally, I will close and delete this branch, and open a new PR. Thanks.

**Pull request closed without merging**
