### PR TITLE
sa3990-sa3999

### PR DESCRIPTION
**Pull request by pjlao307**

### CODE REVIEW

**Comment by doktorsleepelss** [comment]
https://github.com/commaai/comma10k/pull/2008

**Comment by pjlao307** [comment]
@dorkmo that resubmit PR isn't for these masks.

**Comment by pjlao307** [comment]
oops, I meant to @doktorsleepelss

**Comment by pjlao307** [comment]
Actually, nvm, the title is wrong

**Comment by doktorsleepelss** [comment]
My bad. Copy pasted wrong title.

**Pull request merged**
