### PR TITLE
h027-h029 cadmus

### PR DESCRIPTION
**Pull request by qadmus**

### CODE REVIEW

**Comment by qadmus** [comment]
Will fix colors. Used img-labeler.

**Comment by qadmus** [comment]
```
 h027_7e76f042175dc717_2019-06-29--16-05-21_52_853.png HAS BAD SHAPE (1748, 2328, 3)
100%|██████████| 2100/2100 [05:06<00:00,  7.29it/s]
h028_666ab82b82fa3e25_2019-07-20--04-48-29_38_43.png HAS BAD SHAPE (1748, 2328, 3)
h029_2a6d6ba03fb9c4dc_2019-06-07--19-55-48_6_586.png HAS BAD SHAPE (1748, 2328, 3)
100%|██████████| 2100/2100 [05:06<00:00,  6.86it/s]
THERE ARE 3 BAD IMAGES IN THE DATASET [2027, 2028, 2029]
##[error]Process completed with exit code 255.
```

**Comment by VirtuallyChris** [comment]
Thanks so much! Can you just fix up that overlapping lane line on h027?

**Comment by qadmus** [comment]
Working on h027; thank you for the review, will do much better in following rounds.

**Comment by VirtuallyChris** [comment]
No rush! You're a fast learner 😄

**Comment by qadmus** [comment]
That raindrop on h027 concerns me - really part of `my-car`?

**Comment by VirtuallyChris** [comment]
Usually I'd say a rain drop shouldn't be marked but in this case it's reflecting the black portion of the wiper which is mycar so I'd say leave it :)

**Comment by VirtuallyChris** [comment]
Thanks for your hard work! Excited to see more from you soon :)

**Pull request merged**
