### PR TITLE
982-986, 988-989

### PR DESCRIPTION
**Pull request by energee**

### CODE REVIEW

**Comment by pjlao307** [comment]
987 was already submitted so you'll need to remove that from your PR

**Comment by energee** [comment]
Resolved

**Comment by VirtuallyChris** [comment]
Great stuff! Images are anti-aliased in spots, make sure they are only hard edges of the 5 colors.

**Comment by pjlao307** [comment]
It's still failing the check for 985,986 and looks like you still have an old version of 151 that was fixed in master.

**Comment by VirtuallyChris** [comment]
Only 2 pixels left!

**Comment by energee** [comment]
Okay, should be ready to be merged

**Pull request merged**
