### PR TITLE
98, 99, & 100 d mask

### PR DESCRIPTION
**Pull request by kevinharbin**

### CODE REVIEW

**Comment by kevinharbin** [comment]
OK. I'm done. There might be some vehicles not marked, I don't feel confident from this view.

**Comment by timjeparker** [comment]
@kevinharbin I have also been working on maskd 98 and think I identified more vehicles, although it was challenging to tell for sure. It's the first mask I am doing so is taking a bit of time. I hope to have complete tomorrow. I noted in progress on the image spreadsheet (just got access short while ago) but realise you are already working on it too.

**Comment by doktorsleepelss** [comment]
Eh, if it's too ambiguous to tell if there's a car or not,  it probably not a big deal if you don't label it. .  There might be a few things you missed, but I don't see anything obvious. 

but yeah, kevin, make sure you to put your name down in the spreadsheet to avoid people working on the same images.

tim, I'm gonna merge this one, but feel free to post your own later.  I'll merge yours if there's improvements.

**Comment by timjeparker** [comment]
Sounds good and thanks. I have now completed it (00098) and submitted PR for it which I include before for reference. 

It was kind of tricky - trickier than I expected it would be - so some of it is guess/estimate of what it looked like was in the image but hopefully broadly useful. 

https://github.com/commaai/comma10k/pull/3070

**Comment by timjeparker** [comment]
Also, if I should have done anything different with regard to the pull request let me know as was first time doing PR on github. I think it was done as expected but if not let me know as seemed some of the tutorial videos showed different ways of doing it.

**Pull request merged**
