### PR TITLE
4999 tmilost

### PR DESCRIPTION
**Pull request by tmilost**

### CODE REVIEW

**Comment by tmilost** [comment]
What is wrong?

**Comment by doktorsleepelss** [comment]
The resolution is wrong.  If you used img-labeler, make sure you're not using any browser zoom when you save. (you'll see a magnifying glass in the address bar)  And if you have a 4k/retina display, turn off any scaling in the OS.  Also, make sure you're using only chrome.  Chromium varieties don't work.

**Comment by tmilost** [comment]
4k/retina.

Thank you very much.
@doktorsleepelss

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/1787

**Pull request closed without merging**
