### PR TITLE
updated 437, 438,  439

### PR DESCRIPTION
**Pull request by tracminhvu**
Initial PR

### CODE REVIEW

**Comment by VirtuallyChris** [comment]
Looking good! On 439 the left side of the road is good, but the right side you mark the black portion of the divider as a lane line. We had a recent discussion to only label the white portion. Fix that and you should be good!
image

**Comment by tracminhvu** [comment]
fixed 439 as requested.

**Comment by tracminhvu** [comment]
fixing bad color, soon!

**Comment by tracminhvu** [comment]
fix.  bad color 439

**Pull request merged**
