### PR TITLE
h666-h671 Skillfil branch

### PR DESCRIPTION
**Pull request by FilippoBURRO**

### CODE REVIEW

**Comment by pjlao307** [comment]
You'll need to fix the sizes on all 6 images, they should not change from the original mask dimensions.

**Comment by doktorsleepelss** [comment]
If these were done on img-labeler, disable any browser zoom in chrome and any scaling in your monitor settings if you have 4k/retina monitor.  They may cause bad file saves.

**Comment by FilippoBURRO** [comment]
Yes I used Img-labeler and am trying to resize the images but the output
always seems off center. any suggestions?
  screen size is 100% image is at 0, what i mean by output is the mask i
see when i press O

Il giorno sab 3 ott 2020 alle ore 22:04 doktorsleepelss <
notifications@github.com> ha scritto:

**Comment by doktorsleepelss** [comment]
Are you using chrome? Img-labeler really only works properly with chrome.   If you're using windows, make sure scale is set to 100% in display settings (right click on desktop) I don't know what the mac equivalent is.

**Comment by FilippoBURRO** [comment]
I tried recommitting to the branch, making the masks slightly smaller than
the picture in h670 and redrawing from scratch in h661

Il giorno lun 5 ott 2020 alle ore 17:19 Filppo Michelini <
filippomichelini@gmail.com> ha scritto:

**Comment by FilippoBURRO** [comment]
yes chrome on windows, im currently at 100 % but i surely have screwed up
the first commit

Il giorno lun 5 ott 2020 alle ore 17:25 doktorsleepelss <
notifications@github.com> ha scritto:

**Comment by doktorsleepelss** [comment]
Are you trying to resize the image with an external program? If you didn't know, you masks are should be saved in advanced -> Revert From History. You shouldn't have to redo them.

**Comment by FilippoBURRO** [comment]
No I haven't used any other program other than IMG-labeler I was firstly
using the "show existing mask function" and subsequently also used the
revert from history, output still results in a offset, sorry if I'm messing
up this is my first contribution to an open source project, hope I gave you
all the details,
 I will try to
 Modify the mask from the revert checking screen scale,
 resave to my branch
Recommit my branch

Hopefully next processes will be smoother

Il lun 5 ott 2020, 17:56 doktorsleepelss <notifications@github.com> ha
scritto:

**Comment by pjlao307** [comment]
Are you using a 4k display?  Check the scaling factor in windows.

**Comment by FilippoBURRO** [comment]
[image: image.png]
[image: image.png]

Using the 1080 screen of my laptop, size is 100% and all seems good on h666
after i revert the save from the advanced feature, when i output(press O on
the keyboard) the masks shift down and slightly right, I surely messed up
with the scale at my first commit (2 oct, from H666 to H671) but this mask
was made from scratch today where i purposefully paid attention in using
the scale of the software and not that of the browser, What can i do now? I
wouldn't mind starting from scratch again since it's only 6 pictures but
would like to know if i should twig some parameters or anything.

Il giorno lun 5 ott 2020 alle ore 18:30 pjlao307 <notifications@github.com>
ha scritto:

**Comment by pjlao307** [comment]
image
5 of the 6 images are still the wrong dimensions, in fact 2 of them have a different size than the other 3 wrong ones so something weird is going on with your setup but I can't tell what it is.

**Comment by FilippoBURRO** [comment]
it looks like it could have cached the different scale in the browser and is trying to correct it

**Pull request closed without merging**
