### PR TITLE
modified masks for [1098-1100]

### PR DESCRIPTION
**Pull request by elxa-dal**

### CODE REVIEW

**Comment by elxa-dal** [comment]
Hmm it looks like I added some bad colors to the mask, despite only using the pencil tool. I am running Ubuntu 16.04. Any idea what could be going on?

**Comment by VirtuallyChris** [comment]
Very strange! I'd recommend going back through in a program like GIMP or Photoshop making sure to use the 'pencil' tool only and remove aliasing wherever possible. Sometimes when selecting areas with a scribble tool it will have an option to disable aliasing.

**Comment by pjlao307** [comment]
The pencil tool is buggy, use img-labeller instead:
https://erikbernheim.github.io/img-labeler/

**Comment by VirtuallyChris** [comment]
Ohh makes sense, I thought he was using the img-labeler. Maybe we should remove pencil from the repo

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/945

**Pull request closed without merging**
