### PR TITLE
Updated Masks

### PR DESCRIPTION
**Pull request by JamesCCockram**

### CODE REVIEW

**Comment by geohot** [comment]
Thanks for the PR!

0008 has some lane junk on the right side
0011 has a wobbly road
0012 has a speck of road in the middle of nowhere

**Comment by geohot** [comment]
Also, 0015 shouldn't have the left turn arrow as a "lane marking"

**Comment by JamesCCockram** [comment]
I'll quickly update them now

**Comment by JamesCCockram** [comment]
0008, 0011, 0012 and 0015 should be fixed now

**Comment by geohot** [comment]
I think a few of these could still use some refinement, but it's a whole lot better than what's in there. Going to merge :)

It's important to be pixel accurate if possible, each pixel is effectively a classification problem for training the network, and wrong pixels confuse it.

**Comment by geohot** [comment]
Crosswalk shouldn't be labelled as "lane marking" in 15. Masks should be much tighter in 11.

**Pull request merged**
