### PR TITLE
H467-h469

### PR DESCRIPTION
**Pull request by doktorsleepelss**

### CODE REVIEW

**Comment by pjlao307** [comment]
Your size changed on these files.

**Comment by doktorsleepelss** [comment]
Fell asleep before checking. Fixed.

**Comment by pjlao307** [comment]
h469 still has the wrong size

**Comment by doktorsleepelss** [comment]
Caught me making a minor change in h469 after fixing them. I guess the scaling isn't completely fixed on img-laber yet.

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/1603

**Pull request closed without merging**
