### PR TITLE
[1074,1103-1106] dizzy

### PR DESCRIPTION
**Pull request by kdizzy07**

### CODE REVIEW

**Comment by kdizzy07** [comment]
I assumed that when you wrote to remove the bike paths that also applies to their lane markings. Let me know if that's not the case.

**Comment by pjlao307** [comment]
Yes, including lane markings since neither path or marking is used to keep the car in a drivable lane

**Comment by kdizzy07** [comment]
Cool, then it's ready for a re-review.

**Comment by VirtuallyChris** [comment]
Looks great! Thanks so much :)

**Pull request merged**
