### PR TITLE
013,-575-598,-600, 940-944 - Cedricske

### PR DESCRIPTION
**Pull request by cedricske**

### CODE REVIEW

**Comment by cedricske** [comment]
So should I upload the edited ones to this or to a new branch? For some reason I thought we weren't marking reflectors, my mistake!

**Comment by pjlao307** [comment]
Edit the same branch, it will update this PR.  But in the future, keep your PRs to about 5 images because otherwise any issues with any image will hold up all of the images in the PR.

**Comment by cedricske** [comment]
edited and uploaded photos. hope i got this right this time!

**Comment by pjlao307** [comment]
Looks like the files that you updated are in the wrong folder.  They should be in the masks/ folder but they're being added to this PR one level up.  Please move them to the correct folder and update your branch.

**Comment by cedricske** [comment]
Okay, my mistake again. I'll get the swing of this soon.

**Comment by pjlao307** [comment]
You also need to delete the files that are in the wrong location and commit those because this PR still has them in the wrong place.

**Comment by pjlao307** [comment]
Also, looks like you have bad colors in your latest commit.

**Comment by pjlao307** [comment]
Your 13 is conflicting.

**Comment by cedricske** [comment]
ok, I deleted 13

**Comment by pjlao307** [comment]
No don't delete the file!  That would delete it from the master repo as well.  You need to grab the latest version of 13 from comma's master branch and put it into yours.  Then make your edits to it.

**Comment by cedricske** [comment]
I'm not sure how to do that. I feel I am wasting too much of your time with my lack of understanding of how GitHub works. Is there a way I could just give you access to this PR and get it taken care of?

**Comment by pjlao307** [comment]
Closing this as this was merged: https://github.com/commaai/comma10k/pull/371

**Pull request closed without merging**
