### PR TITLE
0101, 0102, 0103, 0104, and 0105

### PR DESCRIPTION
**Pull request by jason-h-simplifi**
Done with 0101 and 0102.  I plan to do all of these.

### CODE REVIEW

**Comment by jason-h-simplifi** [comment]
Done with 0103

**Comment by pjlao307** [comment]
For 102, looks like you're missing part of the hood on the right side.
For 103, that truck in the far distance is missing the label.

**Comment by jason-h-simplifi** [comment]
Fixed!  Lmk if you've got more feedback.

**Comment by pjlao307** [comment]
These look good!

**Pull request merged**
