### PR TITLE
[1210-1215] terror

### PR DESCRIPTION
**Pull request by terror**

### CODE REVIEW

**Comment by terror** [comment]
> _No description provided._

It seems like image labeler and comma pencil yield color issues for me after editing and saving. Very frustrating...

**Comment by doktorsleepelss** [comment]
Have you used any other program to process the image besides img-labeler? Are you resizing it?

**Comment by terror** [comment]
> Have you used any other program to process the image besides img-labeler? This is a direct save from imgr-labeler? Are you resizing it?

The first commit here was resized after saving from image labeler, which I assumed may be the cause of the issue.

However after editing and saving directly from comma pencil and uploading to here the issue still persists.

**Comment by pjlao307** [comment]
Somehow the road edge has anti aliasing on them..

**Comment by terror** [comment]
> Somehow the road edge has anti aliasing on them.. So the resize probably caused it.


> Somehow the road edge has anti aliasing on them.. So the resize probably caused it.

Tried on windows and it worked, can't be bothered with macOS for this type of stuff

**Comment by terror** [comment]
Submitted 1210-1215
Let me know if I need to change some things.



> Somehow the road edge has anti aliasing on them.. So the resize probably caused it.

**Comment by pjlao307** [comment]
I'd recommend you not work off of your master branch, it will make it difficult to keep track of when you're submitting new work. 

Create separate branches for the batch of masks you want to work on so the PRs are kept separate.

I would suggest copying all of your modified masks somewhere and reverting these changes from your master branch. Create a separate branch for all the files you've done and copy them into that branch, then submit a PR for it.

From then on create new branches from your master branch (NOT your working branches!) when you want to work on other batches.

**Pull request closed without merging**
