### PR TITLE
Restore completion status badge with badge continually generated from comma10k spreadsheet

### PR DESCRIPTION
**Pull request by nelsonjchen**
I said I would follow up to #2721 and restore some sort of badge for the comma10k readme eventually.

I followed up on that idea and built https://cellshield.info/ and used it to generate the badge for this PR.

[Completion Status](https://docs.google.com/spreadsheets/d/1ZKqku0cAyWY0ELY5L2qsKYYYA2AMGbgAn4p53uoT3v8/edit#gid=0)

### CODE REVIEW

**Comment by nelsonjchen** [comment]
@doktorsleepelss https://github.com/commaai/comma10k/pull/2721#issuecomment-858185333 

That can be done with https://cellshield.info/ as well. I'll leave it as an exercise for you and to get some feedback about the rudimentary generator on the site.

**Comment by doktorsleepelss** [comment]
Cool tool.  Pretty easy to use. Can you change your PR to this color?

https://img.shields.io/endpoint?color=%232CC627&url=https%3A%2F%2Fcellshield.info%2Fgs%3FspreadSheetId%3D1ZKqku0cAyWY0ELY5L2qsKYYYA2AMGbgAn4p53uoT3v8%26cellRange%3Di1

I think it's kind of hard to read the text with the bright green. 


> That can be done with https://cellshield.info/ as well. 

This one is probably enough now because the new link contains both img and img2.

**Comment by doktorsleepelss** [comment]
Forgot the label override

https://img.shields.io/endpoint?color=%232FBE2A&url=https%3A%2F%2Fcellshield.info%2Fgs%3FspreadSheetId%3D1ZKqku0cAyWY0ELY5L2qsKYYYA2AMGbgAn4p53uoT3v8%26cellRange%3Di1

**Comment by nelsonjchen** [comment]
Yeah the bright green is an issue. Hopefully https://github.com/badges/shields/issues/5497 is resolved so that we can remove the hardcoded colors someday.

OK, no problem, the color has been changed.

**Comment by doktorsleepelss** [comment]
hmm... the label override doesn't seem to work with the new link. 

https://github.com/commaai/comma10k/blob/0c9190b1c5121783b3641b09e6cfbaf45385f475/README.md

**Comment by nelsonjchen** [comment]
> hmm... the label override doesn't seem to work with the new link.  Still says Final Count on my end. 
> 
> https://github.com/commaai/comma10k/blob/0c9190b1c5121783b3641b09e6cfbaf45385f475/README.md

There's no override label query parameter override to the shields.io endpoint of the README in that commit. 

I might have a bug in my generator which I will go checkout soon but you can add it manually.

**Comment by doktorsleepelss** [comment]
ah, my bad.  I missed that parameter in the endpoint page.

Here's the new link. Works now. 

Custom badge

**Comment by nelsonjchen** [comment]
@doktorsleepelss I updated the branch with that badge you've specified. Please take a look.

**Comment by doktorsleepelss** [comment]
Looks good. Thanks.

**Comment by nelsonjchen** [comment]
Awesome! That's one for a gallery if and when I make it.

**Pull request merged**
