### PR TITLE
wjoseph0 117-120 f

### PR DESCRIPTION
**Pull request by wjoseph0**

### CODE REVIEW

**Comment by Polydynamical** [comment]
For 117f I think you drew extra for the lane line in the bottom left: 
image

**Comment by pjlao307** [comment]
Also the lane marking needs to be more accurate
image

**Comment by pjlao307** [comment]
And extend the line to the end
image

**Comment by pjlao307** [comment]
119f - include the black part as part of the lane line
image

**Comment by pjlao307** [comment]
120f - Missing a whole series of dashed lines
image

**Pull request closed without merging**
