### PR TITLE
update 71-79

### PR DESCRIPTION
**Pull request by malawadd**

### CODE REVIEW

**Comment by malawadd** [comment]
updated

**Comment by pjlao307** [comment]
In the future, please check the issues tab and make sure no one else is working on these.  Someone claimed 70-80 but they haven't submitted a PR yet.

**Comment by pjlao307** [comment]
Also, create a new issue and designate what batch you're working on so no one else is duplicating that work.

**Comment by pjlao307** [comment]
Looks like 76 has bad color issues.

**Comment by malawadd** [comment]
i usually do create new issues , but seems i didnt see that one. wouldn't be a lot easier to have like a separate spreadsheet , with all the claimed/done/in progress pics.

**Comment by pjlao307** [comment]
You mean like this: https://docs.google.com/spreadsheets/d/1T1kQx-d6iupRlC4ErCyDO9LM59N9cQTSCeXYDSHM3C8

**Comment by malawadd** [comment]
while on the topic , i want to work on 202-205 but there is a closed issue stating that someone else is working on them , yet i can't find it the one they are talking about

**Comment by pjlao307** [comment]
Check the spreadsheet, if it's marked, look for something that's not.

**Comment by pjlao307** [comment]
Most likely, those marks in the spreadsheet are yours if the only issues listing them are yours.

**Comment by malawadd** [comment]
thank you so much for the sheet , this just made life super easy...

**Pull request merged**
