### PR TITLE
1110 cameron20020

### PR DESCRIPTION
**Pull request by cameron20020**

### CODE REVIEW

**Comment by pjlao307** [comment]
Need to fix bad colors in masks.  Make sure only colors described in the README are present.

**Comment by pjlao307** [comment]
Also please don't work off of your master branch, it will make it difficult to keep track of what you're submitting. You can see this PR was originally for 1110 but now you've also added 1108-1109.
Create separate branches for the batch of masks you want to work on so the PRs are kept separate.

I would suggest copying all of your modified masks somewhere and reverting these changes from your master branch. Create a separate branch for all 6 files you've done and copy them into that branch, then submit a PR for it.

From then on create new branches from your master branch (NOT your working branches!) when you want to work on other batches.

**Comment by cameron20020** [comment]
Cheers, will try to figure this out, new to github and the related nomenclature/procedures in general. Will read up.

**Comment by pjlao307** [comment]
No prob.  Thanks for contributing! :D

**Comment by pjlao307** [comment]
Hi, are you still planning on resubmitting this?

**Comment by cameron20020** [comment]
Yep, forgot about it. Spreadsheet will be updated with new PR in correct branch

**Comment by cameron20020** [comment]
Resubmitted as 967:
https://github.com/commaai/comma10k/pull/967

Thanks

**Pull request closed without merging**
