### PR TITLE
8381 to 8385 Novus

### PR DESCRIPTION
**Pull request by cedricliu**

### CODE REVIEW

**Comment by doktorsleepelss** [comment]
Checks failed because there's too many bad colors, so it can't be merged. It should only be the exact five listed in the readme. You can see that your polygon edges have antialiasing, which is what causing the problem.  Try asking in the discord on how to fix it.   Others in the past have had this problem with photoshop.  

You could also use img-labeler instead, which is probably easier to work with. It's what most people use nowadays.

**Comment by pjlao307** [comment]
If you're using photoshop uncheck the anti-alias option on all selection tools that you use.  Example for the poly tool:
image

**Comment by cedricliu** [comment]
@pjlao307 I see the issue. Is it only work for the lasso tool selection? I tried to create the color block from the pen tool and it does not have the anti-aliasing option for me. Any thoughts?

**Comment by pjlao307** [comment]
I never use pen tool, I only use poly select and fill with foreground or background color.

**Comment by pjlao307** [comment]
Your latest commit should not have changes to the **.gitignore** file.  Please revert that.

**Pull request merged**
