### PR TITLE
1840 to 1846

### PR DESCRIPTION
**Pull request by berno22**

### CODE REVIEW

**Comment by mutusmurum** [comment]
@berno22 your images have different colors than the 5 label colors. If you're using photoshop, please go to menu Image > Mode > Index Colors. Change the colors to "custom" (the 5 official colors). This will force all images to have the correct colors. If you send a new pull request, make sure to update the spreadsheet with the new link.
If you have any questions, enter the discord server (#comma-pencil) and we can solve them: http://discord.comma.ai/

**Comment by berno22** [comment]
I used https://erikbernheim.github.io/img-labeler/

Don’t know what happened with the colors

Best,

Bernard Port





On May 7, 2020, at 6:14 PM, mutusmurum <notifications@github.com<mailto:notifications@github.com>> wrote:



@berno22<https://github.com/berno22> your images have different colors than the 5 label colors. If you're using photoshop, please go to menu Image > Mode > Index Colors. Change the colors to "custom" (the 5 official colors). This will force all images to have the correct colors. If you send a new pull request, make sure to update the spreadsheet with the new link.
If you have any questions, enter the discord server (#comma-pencil) and we can solve them: http://discord.comma.ai/

**Comment by pjlao307** [comment]
1 of them has a bad color, the other 6 have bad sizes
image

**Comment by pjlao307** [comment]
Actually all 7 may have a bad size and 1846 may have both issues but the checker is only reporting the color problem.

**Comment by pjlao307** [comment]
Correction 1846 has the correct size, just a bad color somewhere.

**Comment by pjlao307** [comment]
I just checked 1846 and the mask is completely wrong and the color problem is 1 pixel in the upper left corner of the image

image

**Comment by berno22** [comment]
I've used https://erikbernheim.github.io/img-labeler/

Don’t know what happened with the colors

If you know what I can do better, please let me know.


On May 7, 2020, at 7:38 PM, pjlao307 <notifications@github.com> wrote:

﻿

I just checked 1846 and the mask is completely wrong and the color problem is 1 pixel in the upper left corner of the image

[image]<https://user-images.githubusercontent.com/3270869/81354677-1e321100-9081-11ea-84c2-3d9ecdd341c3.png>

**Comment by pjlao307** [comment]
Check the mask against the image, it's obvious what's wrong with it
image

**Comment by berno22** [comment]
I mean, all the other images

If it's all garbage i don't know what I can do to help, using tools provided on Readme


On May 7, 2020, at 8:34 PM, pjlao307 <notifications@github.com> wrote:

﻿

Check the mask against the image, it's obvious what's wrong with it
[image]<https://user-images.githubusercontent.com/3270869/81357614-0068aa00-9089-11ea-8919-6fafc59a951d.png>

**Comment by pjlao307** [comment]
Need to fix those size and color issues first.  I was just curious what the mask actually looked like.  I didn't bother looking at the other ones because they're the wrong size so can't judge how accurate they are until that's corrected.  Make sure you're not zoomed in or out in the browser when saving in img-labeler.

**Comment by berno22** [comment]
Ok, I'll try again and tag you
Thanks

Best regards,

Bernard Port

On May 7, 2020, at 8:40 PM, pjlao307 <notifications@github.com> wrote:

﻿

Need to fix those size and color issues first. I was just curious what the mask actually looked like. I didn't bother looking at the other ones because they're the wrong size so can't judge how accurate they are until that's corrected. Make sure you're not zoomed in or out in the browser when saving in img-labeler.

**Comment by spektor56** [comment]
Only use chrome with img-labeler, other browsers are known to cause issues when saving like some colours being wrong.  Always CTRL+0 to make sure you have no browser zoom when saving files

**Comment by berno22** [comment]
I'm using Chrome on Mac

Best regards,

Bernard Port

On May 7, 2020, at 9:27 PM, Brett Sanderson <notifications@github.com> wrote:

﻿

Only use chrome with img-labeler, other browsers are known to cause issues when saving like some colours being wrong. Always CTRL+0 to make sure you have no browser zoom when saving files

**Comment by pickdani** [comment]
Your size is still wrong. It's a bug with the image labeler with certain displays. Try setting the zoom in chrome to 50% then exporting. The size should be W: 1164px | H: 874px

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/1277

**Pull request closed without merging**
