### PR TITLE
[1235-1239] mutusmurum

### PR DESCRIPTION
**Pull request by mutusmurum**

### CODE REVIEW

**Comment by mutusmurum** [comment]
Not passing color check for some reason.

**Comment by pjlao307** [comment]
This is because there are incorrect colors on each mask:
image

Make sure the tool you use are set to not anti alias and they use the correct color values described in the README.

Here's your color table for 1235:
image

Notice it has all these greyscale colors in the table.  The issue is you have "Custom".  You need to use "Selective" when saving.  This will only uses the colors that are actually in the file and not the entire color palette.

**Comment by pjlao307** [comment]
However for that image I checked your red (lane) and green (movable) are slightly off color.  
It shows f70605 for red and 10f165 for green.

You'll need to fix that.

**Comment by mutusmurum** [comment]
Resubmited: https://github.com/commaai/comma10k/pull/960

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/960

**Pull request closed without merging**
