### PR TITLE
U002 attempt

### PR DESCRIPTION
**Pull request by cedricske**
Wanted to see if I could do the whole process and submit a user image. I think I did everything correctly.

### CODE REVIEW

**Comment by pjlao307** [comment]
This is not a real submission and should be closed then?

**Comment by dorkmo** [comment]
how were the instructions?

**Comment by cedricske** [comment]
Instructions were good! As for the submission, it doesn't matter to me or not if it gets submitted. Does it hurt to have a labeled image even if it wasn't a struggle area?

**Comment by doktorsleepelss** [comment]
It would be just like another random image. I don't think it would hurt to submit it.

**Comment by pjlao307** [comment]
It does take time to download, mark, review, resubmit though

**Comment by pjlao307** [comment]
Closing this since thi was just a test.

**Pull request closed without merging**
