### PR TITLE
[1621] mgentry10

### PR DESCRIPTION
**Pull request by mgentry10**

### CODE REVIEW

**Comment by pjlao307** [comment]
Please don't work off of your master branch, it will make it difficult to keep track of what you're submitting.  You can see this PR was originally for 1621 but now you've also added 1631-1635.
Create separate branches for the batch of masks you want to work on so the PRs are kept separate.

I would suggest copying all of your modified masks somewhere and reverting these changes from your master branch.  Create a separate branch for all 6 files you've done and submit a PR for it.  

From then on create new branches from your **master** branch (NOT your working branches!) when you want to work on other batches.

**Comment by mgentry10** [comment]
Okay, no problem. I’m sorry.

**Comment by pjlao307** [comment]
Hi, are you still planning on resubmitting this in its own branch?

**Comment by mgentry10** [comment]
Hi,

Sorry, my wife gave birth Tuesday and our baby is still in the hospital. I
will get this done when I get a chance.

**Comment by pjlao307** [comment]
Congrats! And don't sweat it,  I will review, make any changes needed and push this through on your behalf.

**Comment by mgentry10** [comment]
Okay, thank you so much. Again, I am sorry for the confusion.

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/973

**Pull request closed without merging**
