### PR TITLE
0005 - Added oncoming lane

### LINKED ISSUE #496: 0005 missing oncoming road mask

### PR DESCRIPTION
**Pull request by meh-meh**
Closes #496

### CODE REVIEW

**Comment by meh-meh** [comment]
I think we're splitting single pixels in a blurry image. Unless we want to make masks double the resolution to support that, I think we're both as right as is possible.

**Comment by pjlao307** [comment]
Ok then let's wait till another reviewer chimes in.

**Comment by meh-meh** [comment]
Sorry, accidentally clicked the re-review button.

**Comment by meh-meh** [comment]
I tried to see what you're seeing and updated accordingly, but I'm not sure I've given you exactly what you wanted. This is as close as I can get while still believing my result.

**Pull request merged**
