### PR TITLE
images 1983,1985-1987,1989,1990,1992,1994-1998

### PR DESCRIPTION
**Pull request by htrifol**
htrifol updated images 1983,1985-1987,1989,1990,1992,1994-1998

### CODE REVIEW

**Comment by pjlao307** [comment]
Can't ignore it, you have to remove it from your branch.

Also please don't work off of your master branch, it will make it difficult to keep track of what you're submitting in the future. 

Create separate branches for the batch of masks you want to work on so the PRs are kept separate.

I would suggest copying all of your modified masks somewhere and reverting these changes from your master branch. Create a separate branch for all the files you've done and copy them into that branch, then submit a PR for it.

From then on create new branches from your master branch (NOT your working branches!) when you want to work on other batches.

**Comment by pjlao307** [comment]
Are you able to fix the conflict?  You may need to do a new branch and resubmit your PR to fix this.

**Comment by pjlao307** [comment]
Or, copy your files, delete your fork and re-fork it (and create a new branch - don't use master)

**Comment by htrifol** [comment]
Sorry for the delay. Done with another branch as requested, let me know if
any issue this time.

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/1177

**Pull request closed without merging**
