### PR TITLE
h032 fheilz

### PR DESCRIPTION
**Pull request by fheilz**

### CODE REVIEW

**Comment by sshireto** [comment]
changes submitted in #992

**Comment by pjlao307** [comment]
Thanks, but in the future, don't create a new branch, just commit into the branch for the existing PR.

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/992

**Comment by pjlao307** [comment]
Oh wait, disregard that, I didn't realize you're not the original labeller, lol!

**Pull request closed without merging**
