### PR TITLE
jjmachan - 6955 resubmit

### PR DESCRIPTION
**Pull request by doktorsleepelss**
https://github.com/commaai/comma10k/pull/2221

Check out PR 2222 in the PR Reviewer to view my changes. Press space to go back and forth between your original and my changes. 

https://spektor56.github.io/comma10kreviewer/

### CODE REVIEW

**Comment by jjmachan** [comment]
Thank dok for the corrections! I understand it now
Also how should I proceed now, for resubmit I'm a bit confused here. The original one is merged and there is this PR...should I make the changes and upload a new one or will we be merging your correction (this PR) on top?

**Comment by VenomrushCT** [comment]
> Thank dok for the corrections! I understand it now
> Also how should I proceed now, for resubmit I'm a bit confused here. The original one is merged and there is this PR...should I make the changes and upload a new one or will we be merging your correction (this PR) on top?

Once you have it corrected, just go to your branch: jjmachan---6955-resubmit and replace the file in that branch. It will be updated and checked here in this PR

**Comment by VenomrushCT** [comment]
alternatively, you can close this PR and create a new one

**Comment by doktorsleepelss** [comment]
I will be merging this PR with my changes on top of yours.  There's no need for you to do anything else.

I merge every PR I review just so they show up in the PR reviewer when I submit my own PR with the changes.  I keep my PRs open for around 24 hours  before merging just so the submitter could easily take a look at my changes.  Also to give the submitter time to tell if they disagree with any of my changes.  (I'm not perfect)

**Comment by doktorsleepelss** [comment]
I will be making a new PR because this branch now has conflicts due to something Geohot did.

**Comment by jjmachan** [comment]
got it, thanks, guys! I'll get started with another batch of 2 images since I'm starting and it will be easy for the reviewer 😅 (I'll go through the images that have already been annotated and try to get a better idea before I do these 2)

**Comment by doktorsleepelss** [comment]
https://github.com/commaai/comma10k/pull/2235

**Pull request closed without merging**
