### PR TITLE
Updated Masks for 166 to 171

### PR DESCRIPTION
**Pull request by scottadair**

### CODE REVIEW

**Comment by pjlao307** [comment]
Hmm, you're still getting conflicts.  Did you rebase your branch?

**Comment by scottadair** [comment]
What file is conflicting? I’m not seeing it on this side. Yes I rebased, and I have all the upstream changes

**Comment by pjlao307** [comment]
It doesn't say, just that there are conflicts in github which is strange because these images haven't been updated by anyone yet.

It's much easier to work on a branch other than master, just to avoid these issues.

I would delete your fork, re-fork from comma's then create a new branch from master and make your edits there.  That will resolve this. From then on, you can rebase with master and create new branches from that to work on new batches.

**Comment by scottadair** [comment]
Very strange.. Ok, reforking, rebasing and re-pull-requesting (is that a thing?) Third time's a charm?

**Pull request closed without merging**
