### PR TITLE
1222

### PR DESCRIPTION
**Pull request by HarshaLaxman**

### CODE REVIEW

**Comment by pjlao307** [comment]
Unfortunately your images have bad colors in them, meaning there are more colors than the 5 we use for masks. This happens if you use a program like Gimp or Photoshop without disabling aliasing. Go ahead and check these to make sure there's no aliasing in them, there is often options in Gimp or Photoshop to disable aliasing / use the pencil tool at all times will also work.

**Comment by HarshaLaxman** [comment]
Hmm I only used the pencil tool

The commit button didn't work, so I clicked download and moved it to the masks folder

**Comment by pjlao307** [comment]
Pencil tool can be buggy, use https://erikbernheim.github.io/img-labeler/ instead

**Comment by pjlao307** [comment]
Closing this and releasing this so someone can claim it.

**Pull request closed without merging**
