### PR TITLE
h2code 975-979

### PR DESCRIPTION
**Pull request by hassanhibbert**
Closes https://github.com/commaai/comma10k/issues/517

### CODE REVIEW

**Comment by hassanhibbert** [comment]
I'm not totally sure. It seemed too round to be a car. I was thinking it was one of these things https://c8.alamy.com/comp/DF4HAH/propane-gas-tanks-for-lease-or-rent-for-homes-and-business-for-heat-DF4HAH.jpg

**Comment by flamethrower225** [comment]
i wonder if the thing with small wheels is actually a bike and the round thing behind the gate is the propane/gas tank

**Comment by flamethrower225** [comment]
i don't believe its a car though. Wheels are way to small to be a car in my opinion

**Comment by flamethrower225** [comment]
I take my comment back, very convinced it's an old camper

**Pull request merged**
