### PR TITLE
Eliminate the repetition on same beginners doubts

### PR DESCRIPTION
**Pull request by AlexandreSato**

### CODE REVIEW

**Comment by doktorsleepelss** [comment]
Change it to save with the wrong resolution. 

BAD SHAPE is a bit awkward outside of an error message.

**Comment by AlexandreSato** [comment]
> Change it to "save with the wrong resolution."
> 
> BAD SHAPE is a bit awkward outside of an error message.

image
 good?

**Comment by AlexandreSato** [comment]
> Change it to "save with the wrong resolution."
> 
> BAD SHAPE is a bit awkward outside of an error message.

image
Good ?

**Comment by doktorsleepelss** [comment]
Don't think the the new text is needed.  FYI, the reviewer will display any any open PR. Doesn't need to be a draft.

**Comment by doktorsleepelss** [comment]
Oh, my bad. By new text, I only meant the "will automatically upload the images by submitting a Pull Request as DRAFT" part.  For some reason I thought you added that to your last commit. Didn't realize it was there from the start. I'll still merge the first part about saving at the wrong resolution.

**Pull request merged**
