### PR TITLE
1795 Al101

### PR DESCRIPTION
**Pull request by alialbarack**
Trial

### CODE REVIEW

**Comment by whichtom** [comment]
Hey, a few things. The filename shouldn't have a (1) in it, you should overwrite the old mask with your modified one. Delete the file with (1) in it from your fork. The build is failing because the dimensions of the image are incorrect: your file has 1748x2328 but the image must be 874x1164. Don't zoom in/out with your browser as this messes with the image dimensions, if you're using img-labeler use the inbuilt zoom tool. 

Also make sure there is no undrivable in between the car and the road like here:
Screenshot 2020-05-03 at 11 26 43
and
Screenshot 2020-05-03 at 11 26 52
and
Screenshot 2020-05-03 at 11 26 55
and
Screenshot 2020-05-03 at 11 27 01
Also this undrivable at the edge of the screen should be road.
Screenshot 2020-05-03 at 11 27 10
Finally the lane markings in the image don't seem to stop here, so make sure there is no road between the lane markings and the car.
Screenshot 2020-05-03 at 11 27 18

[This YT video on img-labeler from the README](https://www.youtube.com/watch?v=T7s814VJegQ) shows how to do roads so there aren't any undrivable gaps. Also I would recommend not pushing from your master branch but making a specific branch for each batch of images, just if you need to modify the images it makes it easier. If you need any help with anything feel free to join the discord linked in the README, and we're happy to assist.

**Comment by whichtom** [comment]
Easiest thing to do is close this PR, make sure your fork master is up to date with commaai:master (if not, delete your fork then remake it), make a branch from your fork master called 1795 or whatever you want, make the changes, then make a new PR.

**Comment by alialbarack** [comment]
Wow, you guys are fast! I was expecting at least a day to pass before my
first attempt in testing how all this works get reviewed and commented on!
That's awesome! Thanks for the feedback. I'll be sure to delete the fork.
Also, I was using the image labeler zoom in/out function with the scroll
wheel. I made sure to save my work with my browser zoom at 100%. I'm really
not sure what else to do to check for magnification of the image

**Comment by pjlao307** [comment]
Also, make sure the name of the file doesn't change.  This PR is appending " (1)" to the name so it's treating it like a new file in the repo.

**Comment by pjlao307** [comment]
Closing this and releasing claim since there are too many things wrong and would be easier to restart from scratch.
1. Image size is wrong
2. Filename is wrong
3. Undrivables where they shouldn't be

**Pull request closed without merging**
