### PR TITLE
Masks for 1864 and 1865

### PR DESCRIPTION
**Pull request by EgorGorokhov-EG**
Redraw the whole mask for the both pictures. Hopefully, they're better now

### CODE REVIEW

**Comment by pjlao307** [comment]
Need to fix bad colors in masks.  Make sure only colors described in the README are present.

**Comment by EgorGorokhov-EG** [comment]
> Need to fix bad colors in masks. Make sure only colors described in the README are present.

I used Image Labeler and only colors presented there

**Comment by EgorGorokhov-EG** [comment]
And I don't have idea what I've done wrong

**Comment by pjlao307** [comment]
Did you resize the image or do anything to it when you saved it?  Like zoom in/out in the browser?

**Comment by pjlao307** [comment]
Are you on Mac or PC?

**Comment by EgorGorokhov-EG** [comment]
> Did you resize the image or do anything to it when you saved it? Like zoom in/out in the browser?

I only zoomed it in browser, but I didn't anything with the image while saving

**Comment by EgorGorokhov-EG** [comment]
> Are you on Mac or PC?

Windows

**Comment by pjlao307** [comment]
Actualy, the issue is the size of the image changed so most likely you have your zoom set to something other than 100% (or you have retina display that's scaling the image when you save it).

**Comment by EgorGorokhov-EG** [comment]
> Actualy, the issue is the size of the image changed so most likely you have your zoom set to something other than 100% (or you have retina or 4k display that's scaling the image when you save it).

Oh, thanks a lot, but how can I set zoom to 100% in Image Labeler?

**Comment by pjlao307** [comment]
You can't, you have to reset your zoom in the browser to 100% so it doesn't do this when saving.

**Comment by pjlao307** [comment]
CTRL+0

**Comment by EgorGorokhov-EG** [comment]
> You can't, you have to reset your zoom in the browser to 100% so it doesn't do this when saving.

Ok, thanks, I'll try again now

**Comment by pjlao307** [comment]
You don't need to close the PR.  Just push the updated file into the same branch and this PR will get updated.

**Pull request closed without merging**
