### PR TITLE
h601 to h605 Caddde

### PR DESCRIPTION
**Pull request by Caddde**

### CODE REVIEW

**Comment by Caddde** [comment]
The 0005 commit is a mistake, but i dont know how to remove it.

**Comment by pjlao307** [comment]
To remove it, you just need to revert that file back to the one from master (i.e. download that file from master branch and replace your branch with it and push that up to your repo).  It will then remove that file from the PR.

**Comment by Caddde** [comment]
Thanks for the info.

**Comment by pjlao307** [comment]
Doesn't look like it removed it, it thinks it's different from master.

**Comment by Caddde** [comment]
Ok, now i pushed the right one, thanks again.

**Comment by pjlao307** [comment]
Closing this for https://github.com/commaai/comma10k/pull/1953

**Pull request closed without merging**
