### PR TITLE
0320-0324

### PR DESCRIPTION
**Pull request by orrrobert**

### CODE REVIEW

**Comment by nelsonjchen** [comment]
Uh, the sizes of the masks are changed.

**Comment by VirtuallyChris** [comment]
Yeah :/ fix the sizes and we can reassess!

**Comment by nelsonjchen** [comment]
Ah I also see why there isn't a check run. This modifies the original `img` files, not the masks.

**Comment by orrrobert** [comment]
oops tried to save into imgs instead of masks

**Pull request closed without merging**
