### PR TITLE
0540, 0541, 0542, 0543, 0544, 0545, 0546, 0547, 0548, 0549, 0550, 

### PR DESCRIPTION
**Pull request by bigbalthazor**
0540, 0541, 0542, 0543, 0544, 0545, 0546, 0547, 0548, 0549, 0550,

### CODE REVIEW

**Comment by pjlao307** [comment]
In the future, please create an issue and designate which images you're working on so that others know and don't duplicate work.

**Comment by pjlao307** [comment]
Are these masks still being worked on?

**Comment by bigbalthazor** [comment]
haveing computer issue hope to get back to it this weekend

**Comment by bigbalthazor** [comment]
i made the correction and i believe i merged them

**Pull request merged**
