### PR TITLE
h045-h062-cedricske

### PR DESCRIPTION
**Pull request by cedricske**

### CODE REVIEW

**Comment by cedricske** [comment]
My bad on H052 - I'm pretty sure I accidentally combined the original mask with it, otherwise I got extremely sloppy for that one image.

**Comment by cedricske** [comment]
I feel that H045 are parking lot bumper that you would not want to drive over.
image

**Comment by pjlao307** [comment]
That's not a bumper though that's a speedbump
https://image.shutterstock.com/image-photo/photographed-closeup-road-marking-located-260nw-485693611.jpg

**Comment by pjlao307** [comment]
There are no parking lines there.

**Comment by cedricske** [comment]
@pjlao307 - You're right, I'll fix it!

**Pull request merged**
