### PR TITLE
00055 d mask

### PR DESCRIPTION
**Pull request by kevinharbin**
00055 d mask

### CODE REVIEW

**Comment by kevinharbin** [comment]
I think this one is ready.

**Comment by doktorsleepelss** [comment]
Colors are bad because it has anti aliasing.

**Comment by kevinharbin** [comment]
I see that :(. Yeah directly from https://spektor56.github.io/img-labeler/

**Comment by doktorsleepelss** [comment]
Yeah, I'm not sure what's wrong. I still have the same problem.

**Comment by doktorsleepelss** [comment]
Is it only this mask?  If you try making a new mask, does it still save with anti aliasing?

**Comment by kevinharbin** [comment]
It's the same build of chrome as before. maybe too many overlapping layers?

**Comment by doktorsleepelss** [comment]
It happens to me with a single layer.

**Comment by kevinharbin** [comment]
Yes, it's happening on another file now.

**Comment by kevinharbin** [comment]
success!

**Pull request merged**
