### PR TITLE
Added images to imgsd

### PR DESCRIPTION
**Pull request by jonjander**
Added images 31-34

### CODE REVIEW

**Comment by geohot** [comment]
Thanks!

Any way you can get images from different routes and day/night? The more diversity in the dataset the better.

**Comment by jonjander** [comment]
Yes, I’ll add some more images later.

**Comment by spektor56** [comment]
Does no one here have any friends / family?  We don't have a single picture with a passenger yet

**Comment by jonjander** [comment]
@spektor56 @geohot  I added some more images. I have more friends / family if you want. This one can be hard to see [imgsd/00043.png](imgsd/00043.png) but it is my son in the backseat.

**Comment by spektor56** [comment]
> @spektor56 @geohot I added some more images. I have more friends / family if you want. This one can be hard to see [imgsd/00043.png](imgsd/00043.png) but it is my son in the backseat.

yes, people in the back seat, dogs, cats, goats, etc all good :)

**Comment by jonjander** [comment]
Got it. I will ask all my colleagues tomorrow to help me. :) Is it "interior movable" that's most important or do you want like different type of traffic situations outside?

**Comment by geohot** [comment]
Looking good!

The outside doesn't matter, it's different people in different cars that does.

**Pull request merged**
