### PR TITLE
531-540

### PR DESCRIPTION
**Pull request by pjlao307**

### CODE REVIEW

**Comment by pjlao307** [comment]
532 - Not sure what you want changed there?  I did add those tail lights as car and removed the lane line marked on black (tar?)

533 - I don't think that's lane line, that's the white part of the curb that meets the road.  Lines don't go right up to curbs like that.

The rest are updated.

**Comment by VirtuallyChris** [comment]
Yeah I see what you mean about 533, thanks man! I meant that the road looks to ends like it's on a hill like this
image

**Comment by pjlao307** [comment]
If the road ends there those lights in the top right that look like tail lights are flying cars then :D

**Comment by VirtuallyChris** [comment]
Hahaha makes sense xD

**Pull request merged**
