### PR TITLE
h601-h605 bigk

### PR DESCRIPTION
**Pull request by bigk777**
I'm new to this but wanted to help the openpilot community.

### CODE REVIEW

**Comment by pjlao307** [comment]
1. Don't change the filenames, they MUST be the same as the original.
2. All 5 masks have color issues.  Masks should only contain the 5 colors described in the README.md file.

**Comment by bigk777** [comment]
> 1. Don't change the filenames, they MUST be the same as the original.
> 2. All 5 masks have color issues.  Masks should only contain the 5 colors described in the README.md file.
> 3. Don't use your master branch to submit PRs from.  If you work on more masks it's highly likely you're going to get conflicts in the future which will be a pain to correct.

Hello, 

I appreciate the feedback. I apologize for changing the file name. I can change the name and re-upload and edit them if you want.
I followed this [video](https://youtube.com/watch?v=RxqG15zOmCk) that's on the [comma ai official github page](https://github.com/commaai/comma10k).

I also used the [imagine labeler](https://erikbernheim.github.io/img-labeler/) for all these photos. 

Which again is on [official github page](https://github.com/commaai/comma10k). I followed the directions as per the [video](https://youtube.com/watch?v=RxqG15zOmCk) provided. If this information isn't correct please feel free to point me in the right direction. 

If you could provide some clarification on where to submit the pictures  once their edited that would be great as well.

**Comment by pjlao307** [comment]
> If you could provide some clarification on where to submit the pictures once their edited that would be great as well.

You're replacing the existing files in the **masks/** folder so you're basically modifying them, there should never be new files (i.e. renamed files).

**Comment by doktorsleepelss** [comment]
What browser did you use? Img-labler is only compatible with Chrome. Other chromium variants like Brave will have artifacts.

**Comment by bigk777** [comment]
> What browser did you use? Img-labler is only compatible with Chrome. Other chromium variants like Brave/Opera will likely have artifacts.

I do use brave. I'll switch to pure chrome for round 2. Thank you for the heads up. 



> > If you could provide some clarification on where to submit the pictures once their edited that would be great as well.
> 
> You're replacing the existing files in the **masks/** folder so you're basically modifying them, there should never be new files (i.e. renamed files).

Got it, place in "masks/" directory and don't rename the files. I appreciate the feedback, thank you.

**Comment by pjlao307** [comment]
Closing this and releasing the claim on these masks.

**Pull request closed without merging**
